import type { Metadata } from "next";
import "./globals.css";
import "./fonts.css"
import { Web3Provider } from "@/context/Web3Provider";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`s-font antialiased`}
      >
        <Web3Provider>
        {children}
        </Web3Provider>
      </body>
    </html>
  );
}
